### ISSUE TITLE
Your release page is empty

### ISSUE THREAD

**Issue by ChakraaThePanda** [ineedbots/iw4x_bot_warfare#1]
In the instructions, you point out to your release page to download the latest version, but it seems empty:
https://github.com/ineedbots/iw4x_bot_warfare/releases

![image](https://user-images.githubusercontent.com/10036932/102966072-267a7780-44bd-11eb-9d6b-4446ffd2f0ee.png)

**Comment by ineedbots** [comment]
Was intentional as it was ready for a release
