### ISSUE TITLE
Doesn't work with last iw4x update

### ISSUE THREAD

**Issue by TedMosly** [ineedbots/iw4x_bot_warfare#101]
![image](https://github.com/user-attachments/assets/48b22e0f-b21d-4f70-8529-6f00e5fdd968)

**Comment by diamante0018** [comment]
An issue on your side. Clearly, You are using an outdated version of BW.

BW works completely fine on the latest IW4x update if you actually freaking manage to download the latest version. https://github.com/ineedbots/iw4_bot_warfare/releases/tag/v2.3.0
