### ISSUE TITLE
Bot's aim is inaccurate while ADS in 3rd Person Team Tactical mode

### ISSUE THREAD

**Issue by domain1231** [ineedbots/iw4x_bot_warfare#12]
![120254698-5ed07e00-c2c5-11eb-9744-23a2c767c0a3](https://user-images.githubusercontent.com/85142901/120597941-a2bbb280-c480-11eb-8a1c-a814b696441d.png)

Hello, I used to play with bot in private third person mode. But today I finally noticed that Bot's aim is inaccurate while ADS in 3rd Person Team Tactical mode. You know third person mode is official game mode in MW2. 

As you can see in snap shot I captured, while ADS bot aim sideways not aim direct on my head. This happen bots with AR, LMG, SMG automatic weapon and bot with sniper aim and shot well in third person mode.

**Comment by ineedbots** [comment]
Finally got around to fixing this

dcbee17c2541147090fd8e9f0ed222698e34005d
