### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by FearRizzy** [ineedbots/iw4x_bot_warfare#13]
When I try and play with bots and load in I get an error that says "script compile error unknown function httpgetmaps/mp/bots/_bot_http.gsc" not sure how to fix
![IMG_7428](https://user-images.githubusercontent.com/85517937/121075221-28e23c80-c792-11eb-9812-a01b7bc059a5.jpg)

**Comment by CrazyCSIW6** [comment]
How did you fix it? I know this is caused by certain IW4x builds where it just doesn't cooperate with the mod but come on man, don't be a dick and close as completed without explaining the solution
