### ISSUE TITLE
[Request] Select bot names from bots.txt randomly

### ISSUE THREAD

**Issue by Boxhead78** [ineedbots/iw4x_bot_warfare#16]
Currently bot-names are taken from the top to the bottom of the bots.txt file. It would be better in my opinion if these are selected randomly.

Current bot naming if 4 bots are spawned:
a
b
c
d

Desired bot naming if 4 bots are spawned:
a
z
b
k

**Comment by ineedbots** [comment]
iw4x related, not bot warfare related,  

bot warfare doesn't have any control over the naming of bots aside from a bots.txt file
