### ISSUE TITLE
Bot pathing fails if 2 waypoints cross a objective

### ISSUE THREAD

**Issue by Boxhead78** [ineedbots/iw4x_bot_warfare#17]
As far as my observations go, bot pathing is likely to fail if one waypoint to another crosses a sabotage or demolition objective which leads into the bots jumping around the objective, until they decide to do something different or get killed.

I imagine it could be hard to fix due to how the waypoint-system works.

**Comment by ineedbots** [comment]
just have the waypoint graph path around the obstacles,  this would be map specific

**Comment by ForeskinJohn** [comment]
bots still have no idea where to go on salvage after reinstall

**Comment by ineedbots** [comment]
fbb6b98941001c62307b1444cac412f7587b8998
fixed the issue, make sure that mp_compact_wp.csv is deleted from the waypoints folder
