### ISSUE TITLE
Typo 'defualt' in .cfg files

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ineedbots/iw4x_bot_warfare#19]
In serverlanbots.cfg, these are the values

set bots_loadout "defualt"
set bots_loadout_killstreak "defualt"

is it a typo?

**Comment by ineedbots** [comment]
there is no serverlanbots.cfg, bots_loadout or bots_loadout_killstreak dvar...

**Comment by syaifulnizamyahya** [comment]
You were right. it was from iw4x server files. My mistakes. Sorry.
