### ISSUE TITLE
IW4X MW2: Bots seem to be very... erratic

### ISSUE THREAD

**Issue by SoftwareGuy** [ineedbots/iw4x_bot_warfare#2]
Hi there.

Got a quick question. I noticed that this mod is included in the IW4X Modern Warfare 2 distribution, which is cool. However, after setting my server up for bots (setting fs_game, etc), I loaded into the server and had bots spawn. However, this server instance was not running with "thereisacow" and "sv_cheats 1" or "devmap".

The bots were doing really weird stuff, like some would do nothing until I shot an enemy that it saw and then it would start running somewhere else, some would slowly move, some would traverse the map but then seem to be attracted to me and would follow me like a companion, some would have a party at a waypoint.

Bots are configured to do things and they are set to do them (I double checked it to make sure the settings stuck).

Is this a known bug with the IW4X shipped copy of Bot Warfare? The files seem fairly recent from January 2021 in the package.

Can upload a video to show what behaviour they perform. Hope to get this working so I can have a LAN server with bots for a good time.

**Comment by ineedbots** [comment]
upload a clip of this happening cause it doesnt happen on my end

**Comment by SoftwareGuy** [comment]
Sure thing, I’ll try this again tonight.

**Comment by SoftwareGuy** [comment]
Hey, sorry for the delay - I tried the latest version copied into my servers' mods folder and configured the server according to the documentation. I then joined the server and all bots were performing as expected. I gotta git gud now.

I suspect the IW4X shipped mod version is broken. 

I'll close this issue ticket. Thanks a lot.
