### ISSUE TITLE
Request:Map voting menu.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ineedbots/iw4x_bot_warfare#20]
It would be nice if BotWarfare could have map voting menu. Something like this.
https://www.youtube.com/watch?v=pCR8qtpl6bM&ab_channel=GaZaai
https://www.youtube.com/watch?v=psQLG53Pi9Y&ab_channel=nutter

Anyway, I cannot thank you enough for this amazing mod. Great job!

**Comment by ineedbots** [comment]
already has this

https://github.com/ineedbots/iw4x_bot_warfare/blob/master/userraw/maps/mp/gametypes/_gamelogic.gsc#L35

**Comment by syaifulnizamyahya** [comment]
How do we use this? 
Already set scr_voting 1 and scr_voting true. None of them works. Used in dedicated server.

**Comment by syaifulnizamyahya** [comment]
set scr_voting "1"
scr_voting_maps "mp_afghan,mp_subbase,mp_overgrown,mp_compact,mp_overgrown,mp_strike,mp_subbase,mp_cargoship_sh,co_hunted,mp_favela,mp_cargoship_sh,mp_nightshift,mp_cargoship,mp_estate_tropical,mp_checkpoint,mp_cross_fire,mp_cargoship,mp_subbase,mp_brecourt,mp_afghan,mp_shipment,mp_crash_tropical,mp_storm,mp_quarry,mp_terminal,iw4_credits,mp_compact,mp_highrise,mp_highrise,oilrig,mp_rust,mp_compact,mp_trailerpark,mp_cargoship_sh,mp_trailerpark,mp_boneyard,mp_terminal,mp_fav_tropical,iw4_credits,mp_boneyard,mp_afghan,mp_estate,mp_complex,mp_vacant"
