### ISSUE TITLE
How do I know which maps is fully supported?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ineedbots/iw4x_bot_warfare#22]
This is the list of all maps in IW4x. Which of this maps is not supported? Copied pasted from serverlanbots.cfg

//////////////////////////////////////////////////
// MAP ROTATION	TIPS							//
//////////////////////////////////////////////////
//												//
//Example: sv_maprotation "map mp_bloc map mp_" //
//												//
// mp_afghan        	- Afghan				//
// mp_derail        	- Derail				//
// mp_estate        	- Estate				//
// mp_favela        	- Favela				//
// mp_highrise      	- Highrise				//
// mp_invasion      	- Invasion				//
// mp_checkpoint    	- Karachi				//
// mp_quarry        	- Quarry				//
// mp_rundown       	- Rundown				//
// mp_rust          	- Rust					//
// mp_boneyard      	- Scrapyard				//
// mp_nightshift    	- Skidrow				//
// mp_subbase       	- Sub Base				//
// mp_terminal      	- Terminal				//
// mp_underpass     	- Underpass				//
// mp_brecourt      	- Wasteland				//
//												//
//// DLC1 STIMULUS ///////////////////////////////
// Make sure you have them all installed on your//
// server.										//
//												//
// mp_complex       	- Bailout				//
// mp_crash         	- Crash					//
// mp_overgrown     	- Overgrown				//
// mp_compact       	- Salvage				//
// mp_storm         	- Storm					//
//												//
//// DLC2 RESURGENCE /////////////////////////////
//												//
// mp_abandon       	- Carnival				//
// mp_fuel2         	- Fuel					//
// mp_strike        	- Strike				//
// mp_trailerpark   	- Trailer Park			//
// mp_vacant        	- Vacant				//
//												//
//// DLC3 NUKETOWN ///////////////////////////////
//												//
// mp_nuked  	    	- Nuketown 		        //
//												//
/// DLC4 CLASSICS 1 //////////////////////////////
//												//
// mp_cross_fire    	- Crossfire             //
// mp_bloc		    	- Bloc                  //
// mp_cargoship     	- Cargoship             //
//												//
/// DLC5 CLASSICS 2 //////////////////////////////
//												//
// mp_killhouse	   		- Killhouse				//
// mp_bog_sh	    	- Bog					//
//												//
/// DLC6 FREIGHTER ///////////////////////////////
//												//
// mp_cargoship_sh  	- Freighter				//
//												//
/// DLC7 RESURRECTION ////////////////////////////
//												//
// mp_shipment_long 	- Long:Shipment			//
// mp_rust_long     	- Long: Rust			//
// mp_firingrange		- Firing Range			//
//												//
/// DLC8 RECYCLED ////////////////////////////////
//												//
// mp_storm_spring 		- Chemical Plant		//
// mp_fav_tropical 		- Tropical: Favela		//
// mp_estate_tropical 	- Tropical: Estate		//
// mp_crash_tropical 	- Tropical: Crash		//
// mp_bloc_sh 			- Forgotten City		//
//												//
/// SP MAPS to MP ////////////////////////////////
//												//
// oilrig	  	   		- Oilrig				//
// iw4_credits     		- Test map				//
// co_hunted	   		- Village				//
//												//
//////////////////////////////////////////////////

Thanks.

**Comment by syaifulnizamyahya** [comment]
This is my maprotation.

set sv_maprotation "gametype war map mp_afghan map mp_subbase map mp_overgrown map mp_compact map mp_overgrown map mp_strike map mp_subbase map mp_cargoship_sh map co_hunted map mp_favela map mp_cargoship_sh map mp_nightshift map mp_cargoship map mp_estate_tropical map mp_checkpoint map mp_cross_fire map mp_cargoship map mp_subbase map mp_brecourt map mp_afghan map mp_shipment map mp_crash_tropical map mp_storm map mp_quarry map mp_terminal map iw4_credits map mp_compact map mp_highrise map mp_highrise map oilrig map mp_rust map mp_compact map mp_trailerpark map mp_cargoship_sh map mp_trailerpark map mp_boneyard map mp_terminal map mp_fav_tropical map iw4_credits map mp_boneyard map mp_afghan map mp_estate map mp_complex map mp_vacant"

**Comment by ineedbots** [comment]
https://github.com/ineedbots/iw4x_waypoints/tree/fbb6b98941001c62307b1444cac412f7587b8998
and
https://github.com/ineedbots/iw4x_bot_warfare/tree/master/userraw/maps/mp/bots/waypoints
