### ISSUE TITLE
Broken or missing waypoints

### ISSUE THREAD

**Issue by GaryTheNoTrashCougar** [ineedbots/iw4x_bot_warfare#23]
Bots getting stuck in spawn or moving then getting stuck on mp_compact (Salvage)

**Comment by LeRutY** [comment]
That´s the case with the release 2.0.1. If you download and use the current code (and how to install the mod that way) you´re fine then, waypoints for Salvage have been added 2 months ago

**Comment by LeRutY** [comment]
That´s the case with the release 2.0.1. If you download and use the current code (and how to install the mod that way) you´re fine then, waypoints for Salvage have been added 2 months ago

**Comment by GaryTheNoTrashCougar** [comment]
I have the master branch, updated 4 days ago.  In z_svr_bots.iwd there is a waypoints folder which has mp_compact_wp.csv, in maps\mp\bots\waypoints there is salvage.gsc & in _bot_utility.gsc waypoints are referenced.  I'm confused.

**Comment by GaryTheNoTrashCougar** [comment]
Removing mp_compact_wp.csv from waypoints folder fixes this issue, not sure if the file is related to this map or anything but seems to be causing a conflict.

**Comment by LeRutY** [comment]
Oh maybe I don´t have the issue because I have the game set up to automatically load the bots. I just copied everything from "userraw" and pasted it into the mw2 iw4x userraw folder, no need for the iwd file etc.

**Comment by syaifulnizamyahya** [comment]
I cant find mp_compact_wp.csv file anywhere. And I still have issue with Salvage. Any advise?

**Comment by GaryTheNoTrashCougar** [comment]
mp_compact_wp.csv is located in the waypoints folder in z_svr_bots.iwd, which if you followed the instructions in the README.md you probably have it in your IW4x game folder under mods\bots.  z_svr_bots.iwd is in zip format, so if you have 7-Zip, right-click on it, then under 7-Zip select 'open archive', find the file then delete it.  Hope this helps.
