### ISSUE TITLE
Request : Add support for bot to join lobby if at least 1 player join the lobby.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ineedbots/iw4x_bot_warfare#24]
Since the only place where you can have map voting screen is in lobby, is it possible to add support to lobby? Currently, lobby requires at least 2 person before the match can be started (for team based games. not ffa). Is it possible for the bot to join the lobby if player present? and disallow bots to vote map?

Thanks.

**Comment by syaifulnizamyahya** [comment]
I know why the game doesnt start in the lobby when you have only 1 player for team based games. Everytime lobby is loaded, party_teambased is set to 1. Is it possible for this mod to prevent the rule party_teambased  from being resetted?

Thanks.

**Comment by ineedbots** [comment]
not possible    gsc runs when the map is running
