### ISSUE TITLE
mp_compact (Salvage) map is not working.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ineedbots/iw4x_bot_warfare#25]
When I load the map, the bots wants to walk through the wall. It seems the waypoint have issue. 
I install iw4x_full_game and use official release of BotWarfare(z_svr_bots.iwd). 

Any advise? Thanks.

**Comment by syaifulnizamyahya** [comment]
Found the fix. Need to open z_svr_bots.iwd with 7zip and delete mp_compact_wp.csv file from the waypoints folder.

Thanks.

**Comment by Boxhead78** [comment]
I'm currently fixing this. I'm working on the waypoints for all maps currently.

**Comment by ForeskinJohn** [comment]
village also has many issues with ai going into corners and knifing

**Comment by LeRutY** [comment]
Village is in MW3 not MW2, wrong repository

I have changed the waypoints of Favela, Highrise, Invasion, Scrapyard and Quarry so far, added some more but things like the ladders on Favela still don´t work. Quarry has had some really messed up waypoints

**Comment by GaryTheNoTrashCougar** [comment]
Village aka Hunted map name co_hunted, SP to MP map.  I'll have a look at this tomorrow.  Hopefully it's just dodgy waypoints.

**Comment by GaryTheNoTrashCougar** [comment]
Areas the bots were spawning in had no waypoints, so they were getting stuck.  I have added some, just testing it out now then will upload.

**Comment by GaryTheNoTrashCougar** [comment]
Fix for both Salvage & Village [https://github.com/GaryTheNoTrashCougar/iw4x_bot_warfare/archive/refs/heads/master.zip](url)
