### ISSUE TITLE
Waypoints not being loaded

### ISSUE THREAD

**Issue by HarleySalas** [ineedbots/iw4x_bot_warfare#30]
With a few maps; particularly Karachi and Strike are two I'm certain of, they do not seem to load user created/saved wp files. Even as dirt simple as the waypoints I'll link below, it simply just doesnt load it. In the console upon initializing the game, it strictly states

> attempting to read waypoints from waypoints/mp_checkpoint_wp.csv

and proceeds to load the default 196 waypoint file from http.

I have other maps that load waypoints totally fine, however I'm still not 100% that I can isolate it to being map specific, though it does appear to be.

here's the very simple karachi wp file I created, in which it does fail to load (though no errors are provided in console)
`18
258.102 2080.51 -0.395854,1,stand,13.4912 -179.698 0,,
361.175 2114.33 -0.665004,2 0 8,stand,15.4193 -88.4564 0,,
572.278 2156.35 -7.21318,1,stand,17.9022 -15.0732 0,,
-350.598 2087.3 0.333892,4,stand,17.1936 -88.797 0,,
-350.628 1768.69 23.125,3 5,stand,23.0548 -80.7935 0,,
-132.679 1754.31 56.125,4 6,stand,22.0496 -93.7134 0,,
-133.031 1499.04 50.8133,5 7 9,stand,21.8903 -93.241 0,,
-192.698 1461.45 48.5339,6 10,stand,28.8116 -131.083 0,,
348.748 1621.62 13.6777,1 9,stand,8.89893 176.649 0,,
-29.2799 1618.91 61.7374,8 6,stand,38.4741 -175.353 0,,
-487.641 1428.71 34.0899,7 11,stand,28.5699 -173.161 0,,
-636.259 1239.48 8.125,10 12,stand,20.4401 -97.5586 0,,
-653.258 853.237 -0.867595,11 13,stand,14.3921 -87.6544 0,,
-618.063 595.607 8.125,12 14,stand,15.661 -81.9031 0,,
-617.239 336.617 8.125,13 15,stand,19.8853 -14.1614 0,,
-97.9254 312.04 60.4483,14 16,stand,15.2875 0.725098 0,,
42.1435 241.254 81.2863,15 17,stand,24.1095 -42.583 0,,
136.477 85.8983 33.4891,16,stand,28.0975 -57.6892 0,,
`

I'm really unsure if there is potentially any error I'm creating but I'd venture to guess not... I usually load the default waypoints, then go around deleting numerous waypoint markers that are more or less out of the way, so that bots route to higher traffic areas of the map.

**Comment by ineedbots** [comment]
iw4x/cod file system related, it is out of the control of gsc (this mod) to fix this issue, your best bet for overriding the waypoints is to move all the csvs from out of the .iwd, and place them in the root of the mod folder
