### ISSUE TITLE
Is there a way to auto add the bots to a new offline local game without having to open the menu and manually add them?

### ISSUE THREAD

**Issue by phase19** [ineedbots/iw4x_bot_warfare#31]
I was wondering if there is a way to automatically add a preset number of bots to every game that one starts without having to wait for opening the menu once a game is started by hitting the '5' key and selecting manually the amount of bots to add. I was looking at _bot_utility.gsc file and the bots_main_waitForHostTime and bots_main_firstIsHost functions but I am not sure what needs to be changed. In the wiki it also states that bots_main_waitForHostTime default is 10 seconds. I was not able to find where this 10 seconds is being set at. If anyone can help me to add this automatically add bots to a new local LAN game functionality it would be greatly appreciated.

**Comment by phase19** [comment]
I was able to find the following values in _bot.gsc and able to edit them.

```
	if(getDvar("bots_main_GUIDs") == "")
		setDvar("bots_main_GUIDs", "");//guids of players who will be given host powers, comma seperated
	if(getDvar("bots_main_firstIsHost") == "")
		setDvar("bots_main_firstIsHost", true);//first play to connect is a host
	if(getDvar("bots_main_waitForHostTime") == "")
		setDvar("bots_main_waitForHostTime", 1.0);//how long to wait to wait for the host player
```

**Comment by phase19** [comment]
I was able to find a solution to my question by simply editing the following line in _bot.gsc located under mods/bots/z_svr_bots.iwd/maps/mp/bots/_bot.gsc. Simply change the bots_manage_add DVAR to whatever number of preset bots that you want to add to your game excluding yourself. For example, I added 11 bots so that I can automatically get teams of 6 players per team, 11 bots plus myself = 12 players.

`	if(getDvar("bots_manage_add") == "")
		setDvar("bots_manage_add", 11);//amount of bots to add to the game`

**Comment by Mystical-17** [comment]
> I was able to find a solution to my question by simply editing the following line in _bot.gsc located under mods/bots/z_svr_bots.iwd/maps/mp/bots/_bot.gsc. Simply change the bots_manage_add DVAR to whatever number of preset bots that you want to add to your game excluding yourself. For example, I added 11 bots so that I can automatically get teams of 6 players per team, 11 bots plus myself = 12 players.
> 
> ```
> if(getDvar("bots_manage_add") == "")
>       setDvar("bots_manage_add", 11);//amount of bots to add to the game
> ```

After you make the change how to you recompile the iwd file? Every time I try to zip it back and add back to the game the mod no longer works for me.

**Comment by Mystical-17** [comment]
Thanks I managed to figure it out and got my offline lobbies to autofill. Also added in a bunch of random bot names. Now I can play perpetual Ground War and its great.

**Comment by ineedbots** [comment]
please use the bots_manage_fill dvar.
