### ISSUE TITLE
script runtime warning: potential infinite loop in script 5000 > 5000.

### ISSUE THREAD

**Issue by megvadulthangya** [ineedbots/iw4x_bot_warfare#33]
Hi! I get this on a dedicated server multiple maps, when loaded spamming this line forewer...

This is for bad waypoints?  I pulled all of your waypoints from  here: https://github.com/ineedbots/iw4x_waypoints

Then pasted to my mods/mymod/waypoints 

'BTW I dont think thats couse the waypoints, couse when i modify your COD4X Botwarfare  to work with Mitsurugi WWII Mod

Sometimes i get this infinite loop error tooo.... I worked on bots wepon choosing system to not choose modern weapons... with multiple attachment like noobtube '

6423492] Waited 2096 msec for asset 'maps/mp/mp_vacant.d3dbsp' of type 'col_map_mp'.
[   6423494] ------- Game Initialization -------
[   6423494] gamename: IW4
[   6423494] gamedate: Jan 14 2010
[   6426361] -----------------------------------
[   6426365] Loaded 147 waypoints from script.
[   6435188] script runtime warning: potential infinite loop in script 5000 > 5000.

 22335275] Attempting to read waypoints from waypoints/mp_estate_wp.csv
[  22335294] Loaded 257 waypoints from csv.
[  22344128] script runtime warning: potential infinite loop in script 5005 > 5000.

7387457] Attempting to read waypoints from waypoints/mp_cargoship_wp.csv
[   7387470] Loaded 234 waypoints from csv.
[   7396337] script runtime warning: potential infinite loop in script 5000 > 5000.

3751448] Attempting to read waypoints from waypoints/mp_checkpoint_wp.csv
[   3751460] Loaded 196 waypoints from csv.
[   3760644] script runtime warning: potential infinite loop in script 5000 > 5000.

8097914] Waited 3668 msec for asset 'maps/mp/mp_bog_sh.d3dbsp' of type 'col_map_mp'.
[   8097915] ------- Game Initialization -------
[   8097915] gamename: IW4
[   8097915] gamedate: Jan 14 2010
[   8099238] -----------------------------------
[   8099244] Loaded 138 waypoints from script.
[   8108145] script runtime warning: potential infinite loop in script 5000 > 5000.

**Comment by ineedbots** [comment]
Might be because of the old KDTree, newer version doesnt use it anymore. Try the latest version found on the master branch
