### ISSUE TITLE
Votemap Menu

### ISSUE THREAD

**Issue by megvadulthangya** [ineedbots/iw4x_bot_warfare#36]
I try to run with [votemap mod](https://www.moddb.com/mods/map-voting-menu-mod)... But its not working with your mod...  When i copy and paste all of the files for userraw folder...

**Comment by Ceana7** [comment]
@megvadulthangya the author of that mod needs to update it for the newest version of the iw4x client it used to work for me but stopped working once iw4x started getting updates again.

**Comment by megvadulthangya** [comment]
That mod working if you use the mods/bots 
and put the z_svr_bots.iwd
Into it...
but this method making the server unstabile and sometimes the server crash.


Dont work if you use the raw folder method.

**Comment by Ceana7** [comment]
> That mod working if you use the mods/bots and put the z_svr_bots.iwd Into it... but this method making the server unstabile and sometimes the server crash.
> 
> Dont work if you use the raw folder method.

Honestly, I don't know then what the issue is as I didn't try to extensively troubleshoot it when I faced that problem. Alternatively, you could try using the [built-in map voting](https://github.com/ineedbots/iw4x_bot_warfare/issues/20) that was added to bot warfare.

**Comment by megvadulthangya** [comment]
Thank you! The built in is a bunch of crap... 

BTW... Dont need it that feature couse i managed my dedicated server with iw4madmin Dynamic Map Reservoir plugin... to create a random map, random gametype server.
