### ISSUE TITLE
game become laggy adding more than 7 bots

### ISSUE THREAD

**Issue by Hitseditor** [ineedbots/iw4x_bot_warfare#37]
The game runs fine with 7 bots on my laptop with 300fps, but adding more bots lower the fps to 150, and the mouse feels very laggy. Is there a way to improve it, or can I add more bots as enemy, like 6v2 instead of 4v4?

**Comment by Ceana7** [comment]
@Hitseditor Do you happen to be playing in a private match or on a dedicated server? From my experience the private match would hitch or lag when a large number of bots were present in the game however a dedicated server would run completely smooth. I would like to point out though that it has been a very long time since I've tested bots in private match so the issue I mentioned may have been fixed in a newer build of the client.

**Comment by megvadulthangya** [comment]
You need CPU Power for bots, what you expect? o.O

**Comment by Hitseditor** [comment]
> @Hitseditor Do you happen to be playing in a private match or on a dedicated server? From my experience the private match would hitch or lag when a large number of bots were present in the game however a dedicated server would run completely smooth. I would like to point out though that it has been a very long time since I've tested bots in private match so the issue I mentioned may have been fixed in a newer build of the client.
> 
> If you not doing this already you could try running a dedicated server locally just for yourself which is what I've always done if you're willing to do a little bit of extra work. This would also come with the advantage of allowing you to more finely tune your experience such as easily setting XP multipliers and tweaking bot warfare dvars that are not available in the menu.

Thanks for reply. I tried the 2.0.0 version and it works well with 17bots. The mw3 bots also works well. 
I guess the better AI logic caculation for 2.0.1 may cause noticeable input lag. FPS isn't affected, it's basically same for both version. 
I got no issue now and can fully enjoy this mod, and if u got interest in optimizing for the next version, investigate on this may help.

**Comment by Ceana7** [comment]
> > @Hitseditor Do you happen to be playing in a private match or on a dedicated server? From my experience the private match would hitch or lag when a large number of bots were present in the game however a dedicated server would run completely smooth. I would like to point out though that it has been a very long time since I've tested bots in private match so the issue I mentioned may have been fixed in a newer build of the client.
> > If you not doing this already you could try running a dedicated server locally just for yourself which is what I've always done if you're willing to do a little bit of extra work. This would also come with the advantage of allowing you to more finely tune your experience such as easily setting XP multipliers and tweaking bot warfare dvars that are not available in the menu.
> 
> Thanks for reply. I tried the 2.0.0 version and it works well with 17bots. The mw3 bots also works well. I guess the better AI logic caculation for 2.0.1 may cause noticeable input lag. FPS isn't affected, it's basically same for both version. I got no issue now and can fully enjoy this mod, and if u got interest in optimizing for the next version, investigate on this may help.

Glad to hear your issue got resolved.
