### ISSUE TITLE
sv_wwwBaseURL Question

### ISSUE THREAD

**Issue by jetkai** [ineedbots/iw4x_bot_warfare#40]
Hello!

Is it possible to have further information of the contents that is downloaded from the **sv_wwwBaseURL**, provided in the default cfg? I wish to change the path to download from another endpoint. 🥰

## Vars:
set sv_wwwBaseURL "http://rawcdn.githack.com/ineedbots/www_host/main/iw4x/"
set sv_wwwDownload "1"

**Comment by ineedbots** [comment]
This is a CoD4 feature ported over to IW4x,

https://docs.linuxgsm.com/game-servers/call-of-duty-4#fast-download

Instead of having users download custom assets from the gameserver (which can add load) you can redirect the downloads to a http server to host the files.

**Comment by jetkai** [comment]
@ineedbots Thank you! ^^
