### ISSUE TITLE
Waypoints

### ISSUE THREAD

**Issue by Boxhead78** [ineedbots/iw4x_bot_warfare#41]
Decided to share my waypoints here.

- Generally added more routes
- Added more camp spots
- Bots navigate around bomb spots
[waypoints.zip](https://github.com/ineedbots/iw4x_bot_warfare/files/8415367/waypoints.zip)

On most maps except Afghan, brecourt and complex there could be more waypoints for grenades, claymores, javelins

**Comment by ineedbots** [comment]
Thanks, i'll add this into https://github.com/ineedbots/iw4x_waypoints
