### ISSUE TITLE
Hello, I would like to miss something

### ISSUE THREAD

**Issue by pachy98** [ineedbots/iw4x_bot_warfare#43]
I love your bot mods but would like to ask if it is possible to add some features to your iw4x bots.
If you could add a menu that when connecting a player could choose if he wants to play with streaks or specialist and could choose his specialist configuration.
I am Cuban and I play in lan mode with friends here in my country due to the difficult access to the internet and we had a lot of fun with that game and your mods. Thanks in advance this has been translated from Spanish to English with the google translator

**Comment by ineedbots** [comment]
https://github.com/ineedbots/iw4x_bot_warfare/blob/master/userraw/maps/mp/killstreaks/_killstreaks.gsc#L32

Specialist can be enabled by setting the `scr_specialist` dvar to `1` and setting your killstreaks to ONLY the nuke.

Having players select which perks they get for each streak is out of scope.

**Comment by pachy98** [comment]
my idea is to do something like in mw3 that you can only nuke in specialist mode that with streaks the nuke is not activated
and the other question is that many users have other options in their killstreaks besides nuke

**Comment by pachy98** [comment]
something like this a menu like this that allows you to select  https://www.youtube.com/watch?v=Cd36PY9QKNY
