### ISSUE TITLE
17 bots makes my custom game extremely laggy

### ISSUE THREAD

**Issue by edustu** [ineedbots/iw4x_bot_warfare#45]
I play bot warfare on iw5 pluto and it runs very well, but on iw4x I get 350+ fps on a custom game with no bots, and as soon as I add 17 bots (or even less) it gets extremely laggy and the fps drops to 120sh (feels like 40 though). Is there a fix for it without having to create a dedicated server?? I just want to play it in custom games, thx in advance  : )

**Comment by ineedbots** [comment]
engine related, iw5 (mw3) doesnt have this issue because the game is better optimized for separating the server thread and the render thread. iw4x could make a patch to fix this, I believe alteriwnet or fourdeltaone had this fixed once upon a time.

dedicated server is the only solution right now.

**Comment by ghost** [comment]
Hey guys try this.
Set `com_maxfps` to 0
For some reason, limiting the fps to less than a certain threshold (Monitor refresh rate possibly) makes the game have inconsistent frame times.
![image](https://github.com/ineedbots/iw4_bot_warfare/assets/143520149/bc45674f-e0b3-4a89-bdb5-8d78ceb0d343)

The moment I change `com_maxfps` to 0 (AKA unlimited), the issue goes away.
![image](https://github.com/ineedbots/iw4_bot_warfare/assets/143520149/a827ec70-147a-4cc4-8dfc-333f0f6c1f93)

**Comment by ineedbots** [comment]
iw4 actually has a seperate server thread like the console version does, as well as pc iw5. this is a iw4x issue as they force it back to the old single thread for the server thread for some reason...

https://github.com/iw4x/iw4x-client/blob/develop/src/Components/Modules/Threading.cpp#L145

**Comment by Espionage724** [comment]
Is there something to check when bot count starts to affect the engine? (something on netgraph, high CPU0, log, etc)

I heard 1000Hz on mouse could affect MW2 too (high single-core use and/or engine calcs with camera/scene and mouse position updates)
