### ISSUE TITLE
Bots stucks at map Winter Crash and names don't changes

### ISSUE THREAD

**Issue by clx127** [ineedbots/iw4x_bot_warfare#50]
Hi! I'm using iw4x latest version and bots warfare latest version. So i noticed that bots stucks on map Winter Crash, also "bots.txt" in userraw folder nothing changes in game:|

**Comment by ipkpjersi** [comment]
For me, I get stuck loading winter crash, at least on Third-Person Search & Destroy:
![](https://i.imgur.com/BZnLfoi.png)

Using iw4x 0.7.5 with iw4x_bot_warfare 2.1.0

**Comment by ineedbots** [comment]
not mod related, by client related.

**Comment by ipkpjersi** [comment]
Yep, even though it only happened with the mod loaded, it no longer happens with iw4x 0.7.6 so this is now fixed.
