### ISSUE TITLE
Search & Destroy (especially Third-Person) bot waypoint issues on Backlot, Chinatown, Countdown, Pipeline, and Downpour 

### ISSUE THREAD

**Issue by ipkpjersi** [ineedbots/iw4x_bot_warfare#51]
Hi,

I am using iw4x 0.7.5 with iw4x_bot_warfare 2.1.0. In Search & Destroy and especially third-person Search & Destroy, on certain maps, the bots get "stuck" like they don't have waypoints or something. The only settings I change are killcam off and third-person on.

On the defending side of Backlot in S&D, bots often get stuck in corners, like this one: 
![](https://i.imgur.com/bBYmVj9.png)

On the attacking side of Backlot in S&D, especially third-person S&D but also sometimes first-person S&D, the bots get stuck in the spawn area:
![](https://i.imgur.com/1hNOclx.png)

In third-person S&D, it's like the bots don't even try to destroy the objective, just run in circles - do they require first-person camera for waypoints or something?

This happens to a lesser extent on Bloc, at least Block still remains playable but is still a bit "weird" in terms of third-person S&D waypointing vs first-person S&D.

It's a shame that this mostly seems to affect third-person S&D since it's my favorite game mode.

Bots are also getting stuck on these maps in S&D as well: Chinatown at spawn running around looking at the ground, Countdown at spawn running around looking at the ground, Pipeline at spawn and on the other side they get stuck on walls, and Downpour stuck behind objects.

**Comment by ipkpjersi** [comment]
Now that Winter Crash no longer crashes on loading, it seems like it also has waypoint issues, you can see here in this TDM that the bots seem to be stuck at the start: 
![](https://i.imgur.com/8vSIp29.png)

**Comment by ForeskinJohn** [comment]
waypoints for the three new maps added to IW4X need to be created, more maps are planned too, i may start attempting to create some myself

**Comment by ForeskinJohn** [comment]
will definitely add to these bounties when i get my check, id wait until the new map set comes out, as a few maps from MW3 are planned for the next stable release of IW4X according to the discord.

**Comment by ipkpjersi** [comment]
It seems like this issue is invalid, no bounty is required thankfully. There's actually a fork of this repo by XLabsProject which seems to have waypoints that work perfectly. I cannot replicate this issue with iw4x r4226 and iw4x_bot_warfare v2.3.2 so I will go ahead and close this issue.
