### ISSUE TITLE
Map selection screen messed up with latest update

### ISSUE THREAD

**Issue by ForeskinJohn** [ineedbots/iw4x_bot_warfare#52]
map selection screen seems to have repeating listings of maps, along with some missing ones, not sure what causes this but its quite inconvenient if you arent using dedicated server

**Comment by ineedbots** [comment]
not mod related, but client related

**Comment by ForeskinJohn** [comment]
cant you make a custom client like you did with T4M for IW4X? the latest version of IW4X probably will never support this mod again

**Comment by ForeskinJohn** [comment]
that or link me to the original IW4X files? i just want to enjoy modern warfare 2 offline again
