### ISSUE TITLE
script compile error unknown function httpget maps/mp/bots/_bot_http.gsc

### ISSUE THREAD

**Issue by plasterboy83** [ineedbots/iw4x_bot_warfare#56]
"script compile error unknown function httpget maps/mp/bots/_bot_http.gsc" is the error message that appears after I attempt to load any map with the mod. Bot warfare is the only mod I have, and I'm playing on iw4x version 0.7.7. I have bot warfare version 2.1.0 and I've never gotten this error message before.
![image](https://user-images.githubusercontent.com/100046924/210150098-35c0ccf1-0d6b-4a64-b5b4-d00d246aad59.png)

**Comment by plasterboy83** [comment]
just reinstalled the game, same error. I think it has to do with the new iw4x version.

**Comment by PnguinFlyer** [comment]
I have the same issue. Redownloaded iw4x and bot warfare and it still pops up the same issue only while trying to play with bots.

**Comment by CrazyCSIW6** [comment]
The latest IW4x updates deprecated unsafe functions that this mod was utilising.
See https://github.com/XLabsProject/iw4x_bot_warfare for an updated version that fixes this error message.

**Comment by plasterboy83** [comment]
thanks @CrazyCSIW6 
for anyone that needs to know, download [this version](https://github.com/XLabsProject/iw4x_bot_warfare) of bot warfare, fixed the issue for me.
https://github.com/XLabsProject/iw4x_bot_warfare
