### ISSUE TITLE
Can you look into this "Scripting error"?

### ISSUE THREAD

**Issue by Raiden1964** [ineedbots/iw4x_bot_warfare#57]
![Skärmbild 2023-01-09 164305](https://user-images.githubusercontent.com/117574555/211349434-76f18f0f-dfe7-4f87-b94a-8d8bbe9eac25.png)

**Comment by theminecraften66** [comment]
I am having the same error after downloading and atemping to play the game on the launcher. i never had issues before using the launcher but with it im having this issue so i think its the launcher.  
just a guess tho

**Comment by ineedbots** [comment]
#53
