### ISSUE TITLE
What Causes This? 

### ISSUE THREAD

**Issue by ForeskinJohn** [ineedbots/iw4x_bot_warfare#58]
I finally was able to get 0.77 working again, and now i get this error after attempting to start a private match.
![Screenshot (39)](https://user-images.githubusercontent.com/64999311/215313373-1854c0e1-c243-41f9-8c2a-d5f7c5baadfb.png)

**Comment by ForeskinJohn** [comment]
Figured out the fix, avoid downloading this mod from here at all costs, get the actual maintained release here: https://github.com/XLabsProject/iw4x_bot_warfare

**Comment by theminecraften66** [comment]
you say maintained release but i get about 5-7 frames while playing with your version of the mod where as i didn't have that issue before. any idea why this is happening

**Comment by theminecraften66** [comment]
ah that explains alot thanks for helping me

**Comment by ineedbots** [comment]
#53
