### ISSUE TITLE
Domination Mode

### ISSUE THREAD

**Issue by Seanny101** [ineedbots/iw4x_bot_warfare#60]
I cannot seem to set game options for this Mode.
Other Modes like Search and Destroy and all other Modes I have checked so far ,let me set variables like Number of Respawns ,starting Health ,all that sort of thing.
When I pick Domination ,which does work by the way with the bots ,the SETUP GAME TAB is greyed out and I cannot set the variables like I would like.
I am using the newest version ,

**Comment by balogune** [comment]
open the console and type/reloadmenus. thats the workaround i found. hope this helps

> I cannot seem to set game options for this Mode. Other Modes like Search and Destroy and all other Modes I have checked so far ,let me set variables like Number of Respawns ,starting Health ,all that sort of thing. When I pick Domination ,which does work by the way with the bots ,the SETUP GAME TAB is greyed out and I cannot set the variables like I would like. I am using the newest version

open the console and type/reloadmenus. that should be the workaround

**Comment by Seanny101** [comment]
Thank you.
I will try this .
I recently thought of this issue again -been a while since I asked question.
Bit of a coincidence.


Sent from Mail for Windows

**Comment by Seanny101** [comment]
I tried the suggestion.

Lo and Behold ,
Eureka ,
it worked.

Thanks a lot.
Lifesaver- maybe not literally ,but this is cool.

Sent from Mail for Windows

**Comment by ineedbots** [comment]
This is a non-mod related issue
