### ISSUE TITLE
problem loading mod

### ISSUE THREAD

**Issue by meh721** [ineedbots/iw4x_bot_warfare#62]
so I just started playing MW2 for the PC recently, I haven't tried playing in any public lobbies in fear of being hacked, so I wanted to use this here bot mod for some offline play. however, after I installed the mod and moved the mod file into my game directory and started the game, upon trying to launch the mod, the game closes out, tries to restart itself, and gets stuck in an infinite invisible screen (not a black screen, the app is open and running, but the window does not show, and my desktop becomes inflated and I'm unable to interact with it. any help please?

**Comment by balogune** [comment]
https://github.com/XLabsProject/iw4x_bot_warfare. try this version of the mod

**Comment by ineedbots** [comment]
Client related issue
