### ISSUE TITLE
"script compile error, selectclass already defined"

### ISSUE THREAD

**Issue by BoogieWu** [ineedbots/iw4x_bot_warfare#65]
Getting this error every time I try to boot up a map with this mod, it would just kick me back to the menu and it would give me this error.

**Comment by Mannan2008** [comment]
Yep Same with me

**Comment by BoogieWu** [comment]
> Yep Same with me

Seems to me that the destruction of the Xlabs launcher has ruined some of the bot warfare mods, or they just lack proper updates and can't keep up with newer versions of iw4x etc.

Not even the newer iw4x version of bot warfare works, it just gives the same error when you try to use it.

**Comment by ineedbots** [comment]
not mod related, go to iw4x for a solution
