### ISSUE TITLE
Crash when too many bots in game

### ISSUE THREAD

**Issue by captinwill** [ineedbots/iw4x_bot_warfare#68]
all three dump files

[iw4x-r4303-128-g4badcdd0-dirty-20240127165830.dmp](https://github.com/ineedbots/iw4_bot_warfare/files/14073961/iw4x-r4303-128-g4badcdd0-dirty-20240127165830.dmp)
[iw4x-r4303-128-g4badcdd0-dirty-20240127170219.dmp](https://github.com/ineedbots/iw4_bot_warfare/files/14073962/iw4x-r4303-128-g4badcdd0-dirty-20240127170219.dmp)
[iw4x-r4303-128-g4badcdd0-dirty-20240127170813.dmp](https://github.com/ineedbots/iw4_bot_warfare/files/14073963/iw4x-r4303-128-g4badcdd0-dirty-20240127170813.dmp)

**Comment by ineedbots** [comment]
disable your cheats please
