### ISSUE TITLE
What is the process to modify the mod?

### ISSUE THREAD

**Issue by PanzerFowst** [ineedbots/iw4x_bot_warfare#69]
## Summary:

Probably a dumb question, but I created a fork of this repo so that I could have fun modifying some of the bot chatter or the bot names, but I don't know how to correctly modify the files it seems?  Whenever I launch a dedicated server running the mod with my changes, the bots fail to load.  I can't see any error messages or anything crashing, so I am kinda confused.

Is it possible for someone to just open the `z_svr_bots.iwd` file, make some changes, put it back, and run the mod again?

## Stuff I did:

I realized a little bit ago that if I renamed the `.iwd` file to a `.zip` and extracted it, I could see all the source code and go in and modify things.  Well, I did that in the `_bot_chat.gsc` file and then I zipped everything back up and tried to put it back how I found it, but I can't seem to get that to work.

I even tried just unzipping and then zipping the `z_svr_bots` file back up and change the extension back to `.iwd`, but even that would result in the mod not working.  Am I just missing something in the way you package the mod?

**Comment by PanzerFowst** [comment]
I also want to add that I cannot thank you, @ineedbots enough for this mod!

My family/friends and I have had a lot of fun playing IW4x together with LAN parties, but this mod made it way more enjoyable instead of matches being 2v3 or maybe 3v3 if we got lucky.  This mod was perfect for us and really just is so nice to have a full lobby of only people we know without having to go searching for random online lobbies.

My hope is that I can change up some of the bot messages to throw in some inside jokes, but even if I can't, we still love and will use the mod regardless!  =)

**Comment by ineedbots** [comment]
It looks like you have the right idea, just open the .iwd (its just a zip file) with a zip unachiver, make changes to the .gsc files, and save the archive (make suure it still ends with .iwd)

**Comment by PanzerFowst** [comment]
I feel like I've done that, but maybe not correctly?  Here's what I do:
1. Rename extension from `.iwd` to `.zip`.
2. Right-click in Windows Explorer and click `Extract All...` and extract the contents to my `Downloads` folder since I can't extract inside the `Program Files (x86)` folder.
3. Open the extracted folder, navigate to the `.gsc` file with the bot chat strings and modify only the strings.
4. Save the files.
5. Right click the folder `z_srv_bots` folder and go to `Send to` → `Compressed (zipped) folder`.
6. Rename the extension from `.zip` to `.iwd`.
7. Place the new `.iwd` folder into the same location I got it from (I keep the original `.iwd` file in the same location but renamed to `z_srv_bots-old.zip`.).
8. It looks like this:
![image](https://github.com/ineedbots/iw4_bot_warfare/assets/36005167/5c326963-6f70-48ed-8c4b-59a31be1e9c9)

But the bots don't load when I load the LAN server.

I have done the exact same thing where I didn't change and of the code (so omitting steps 3 and 4), and the same thing happens.  Is that normal?

**Comment by PanzerFowst** [comment]
It seems I am getting this error whenever I launch with a modified `.iwd` file...
```
[error 2147942402 (0x80070002) when launching `iw4x.exe  -dedicated +set fs_game "mods/mp_bots" +set sv_lanonly "1" +set net_port "33111" +exec BOTWAREFARE.cfg +set party_enable "0" +map_rotate']
```

![image](https://github.com/ineedbots/iw4_bot_warfare/assets/36005167/849b7907-e28d-4287-b8d1-130dab20770c)

**Comment by iYawnz** [comment]
To modify bot names all u have to do is adding a bots.txt file in the z_svr_bots.iwd "zip" file. To open it you can use anything like WinRar. open the txt time and add names from top to bottom each new name under eachother and to add clantags to them do TheirName,Clantag. To edit anything related to chatter there is a file in z_svr_bots.iwd: maps\mp\bots named _bot_chat.gsc. You can edit there some lines that are already existent. Hope that helps

**Comment by PanzerFowst** [comment]
Hmmmm...  Maybe I'll try WinRar instead of just the normal File Explorer because at this rate, I'm not sure what it is?

**Comment by iYawnz** [comment]
> Hmmmm... Maybe I'll try WinRar instead of just the normal File Explorer because at this rate, I'm not sure what it is?

Yes, use Winrar and make the .iwd files being opened by Winrar as default. I do this all the time works perfectly fine

**Comment by PanzerFowst** [comment]
Alrighty, I moved my `.iwd` file to my Downloads directory, renamed the file to `.zip`, used WinRar to Extract the folder, made no modifications, used WinRar to create `.zip` by clicking `z_svr_bots` folder and clicking Add and then ZIP as Archive format and then OK, and then renamed file to `.iwd`, put it back in my `mods` folder and the script is still broken.

Looks like it is failing on the `scripts/_aimassist::init` function...

*Original `.iwd` file:*
![image](https://github.com/ineedbots/iw4_bot_warfare/assets/36005167/9d6504d1-9452-4e47-8083-2518cb29d415)

*WinRar unzipped and zipped again `.iwd` file:*
![image](https://github.com/ineedbots/iw4_bot_warfare/assets/36005167/387de189-e143-418d-b1a5-e43a1a713b21)

**Comment by iYawnz** [comment]
> Alrighty, I moved my `.iwd` file to my Downloads directory, renamed the file to `.zip`, used WinRar to Extract the folder, made no modifications, used WinRar to create `.zip` by clicking `z_svr_bots` folder and clicking Add and then ZIP as Archive format and then OK, and then renamed file to `.iwd`, put it back in my `mods` folder and the script is still broken.
> 
> Looks like it is failing on the `scripts/_aimassist::init` function...
> 
> _Original `.iwd` file:_ ![image](https://private-user-images.githubusercontent.com/36005167/305663257-9d6504d1-9452-4e47-8083-2518cb29d415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTEwMTYsIm5iZiI6MTcwODIxMDcxNiwicGF0aCI6Ii8zNjAwNTE2Ny8zMDU2NjMyNTctOWQ2NTA0ZDEtOTQ1Mi00ZTQ3LTgwODMtMjUxOGNiMjlkNDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDIyNTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiY2U0NjU2YzM0ZGU0NjMzNDNlMjBhNjA5MTcxMmVhOGEyOTI5MjhlYWI3MjE5ZDQwYThkZDRlYTE4YmY5ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wi0reXflsXRnnxGW8LMXDomujJf-hyEGJawzqg4Jz-c)
> 
> _WinRar unzipped and zipped again `.iwd` file:_ ![image](https://private-user-images.githubusercontent.com/36005167/305663735-387de189-e143-418d-b1a5-e43a1a713b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTEwMTYsIm5iZiI6MTcwODIxMDcxNiwicGF0aCI6Ii8zNjAwNTE2Ny8zMDU2NjM3MzUtMzg3ZGUxODktZTE0My00MThkLWIxYTUtZTQzYTFhNzEzYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDIyNTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0M2NmN2YxZWRhZjA4MWIyODI4YWYwZDFhNzRiNjcyMzdhZDhmZmNhNTkzNzY1MTc1MzY1YTc5ZWYyZTY3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DUaAFB_c92BNoZRYv7KRLsYwLb5equWiDHCFK0uCBkE)

No i did not say renaming the file extention. Just open the .iwd with winrar. If it runs fine but after you have changed some code it stops working then that is a code issue

**Comment by PanzerFowst** [comment]
Uhmmmmmm...  Well, that seemed to work...  Thanks, @iYawnz!!!

![image](https://github.com/ineedbots/iw4_bot_warfare/assets/36005167/34050292-f5c5-40b0-ba2d-5a70fd6ac321)

![image](https://github.com/ineedbots/iw4_bot_warfare/assets/36005167/9bd51d0b-26d8-4f0b-872f-2fab04eddb1b)

![image](https://github.com/ineedbots/iw4_bot_warfare/assets/36005167/9444e789-5df3-4665-aeeb-8c6df0161bae)

Now the obvious question: Why does this work this way?  How does does ineedbots do releases then??  I think I can work with this in my own repo, but it'll be a BIT weird.  xD

**Comment by ineedbots** [comment]
iwds are literally just zip files, just renamed

**Comment by NazgulCoder** [comment]
> To modify bot names all u have to do is adding a bots.txt file in the z_svr_bots.iwd "zip" file. To open it you can use anything like WinRar. open the txt time and add names from top to bottom each new name under eachother and to add clantags to them do TheirName,Clantag. To edit anything related to chatter there is a file in z_svr_bots.iwd: maps\mp\bots named _bot_chat.gsc. You can edit there some lines that are already existent. Hope that helps

sorry for replying on a very old issue, but do you know if you can rename bots by adding bots.txt inside the z_svr_bots.iwd for CoD WaW too? Do you know if this works on an older version of bot warfare that does not require T4M?

**Comment by iYawnz** [comment]
I’m pretty sure it does. Maybe it’s another file name structure you could
google it or look around for a bit. I think often CoD have a similar file
path structures so you could figure out what file it is.

Op ma 3 feb 2025 om 23:14 schreef Nazgul ***@***.***>

**Comment by NazgulCoder** [comment]
> I’m pretty sure it does. Maybe it’s another file name structure you could
> google it or look around for a bit. I think often CoD have a similar file
> path structures so you could figure out what file it is.
> 
> Op ma 3 feb 2025 om 23:14 schreef Nazgul ***@***.***>
> […](#)

Do you know if this is possible for the Bots on T4 mod too?

**Comment by iYawnz** [comment]
Its should work the same sort of way yes, there ia also a discodd you could
join if you are unable to figure it out. Best of luck

Op di 4 feb 2025 om 19:27 schreef Nazgul ***@***.***>
