### ISSUE TITLE
Boys don’t do anything

### ISSUE THREAD

**Issue by dylnft** [ineedbots/iw4x_bot_warfare#7]
I have installed the mod no worries, all the options work. I can spawn in all bots.

BUT, when they get close to each other or me, they target but do not do anything and usually get stuck. Sometimes a random bot will run around knifing here and there, but they do not shoot guns at all. 

There ping is 999 not sure if that has anything to do with it.

**Comment by ineedbots** [comment]
Make sure to use iw4x 0.6.1+ and the bot warfare v2.0.0+,  its most likely you are using an outdated version of either
