### ISSUE TITLE
python scripts for waypoint modification/fixing

### ISSUE THREAD

**Issue by Bluscream** [ineedbots/iw4x_bot_warfare#74]
https://github.com/Bluscream/iw4/blob/main/waypoints.py
https://github.com/Bluscream/iw4/blob/main/waypoints/WaypointFile.py
https://github.com/Bluscream/iw4/blob/main/waypoints/Waypoint.py

**Comment by diamante0018** [comment]
Okay?
You are asking for a code review? What is this about?
I don't see these being useful to any person other than yourself since in at least one of these scripts you are hardcoding a Windows path. Python stuff should be able to run on any platform not just your PC.

**Comment by Bluscream** [comment]
> Okay?

Okay!

> You are asking for a code review? What is this about?

Not really, i mean its not that im not happy with constructive feedback, and even more actual improvements. But this is more of a reference for someone that might need this/picks up on it later.

> I don't see these being useful to any person other than yourself since in at least one of these scripts you are hardcoding a Windows path. Python stuff should be able to run on any platform not just your PC.

Python code is open source by design. I wont create a config file for something so niche when all someone has to do is change a few variables around to fit their needs

**Comment by ineedbots** [comment]
no issue here, it's more for info
