### ISSUE TITLE
[Feature Request] No bots until first player spawns

### ISSUE THREAD

**Issue by Bluscream** [ineedbots/iw4x_bot_warfare#76]
I would like to request two new variables:

- [ ] `bots_waitForFirstSpawn` Makes bots wait to join the server until the first player spawns, regardless of wether he's host or not.
- [ ] `bots_leaveAfterLastPlayer` Makes bots leave after the last player left the server, effectively ending the round (Maybe with an additional timedelay to allow for reconnects)

**Comment by ineedbots** [comment]
Completed as `bots_manage_fill_watchplayers` dvar. Use bots_manage_fill_kick to prevent the bots from being removed
