### ISSUE TITLE
[Bug] Bots Stuck on loop with latest version (v2.2.0)

### ISSUE THREAD

**Issue by iYawnz** [ineedbots/iw4x_bot_warfare#80]
Bots get stuck in a loop not advancing into the map in realistic pase. They keep backtracking/follwowing eachother and hardly come out of their spawn. Not map specific it happens on every map currently. 

Video as reference: 
https://streamable.com/8le29y

**Comment by ineedbots** [comment]
are the afghan waypoints messed up?

**Comment by ineedbots** [comment]
https://github.com/ineedbots/iw4_bot_warfare/blob/master/scriptdata/waypoints/mp_afghan_wp.csv
looks like it hasnt changed in 3 months, and i tested, no issues, make sure that the waypoints are being loaded

**Comment by ineedbots** [comment]
![image](https://github.com/ineedbots/iw4_bot_warfare/assets/751729/9d9bef68-5a30-432a-9e2e-18ef79bbd6a5)

**Comment by ineedbots** [comment]
![image](https://github.com/ineedbots/iw4_bot_warfare/assets/751729/da236703-d1ec-4922-9149-152afacaeee3)
playing just fine no issues on my end

**Comment by iYawnz** [comment]
> ![image](https://private-user-images.githubusercontent.com/751729/306356684-9d9bef68-5a30-432a-9e2e-18ef79bbd6a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDk1NDEsIm5iZiI6MTcwODQ0OTI0MSwicGF0aCI6Ii83NTE3MjkvMzA2MzU2Njg0LTlkOWJlZjY4LTVhMzAtNDMyYS05ZTJlLTE4ZWY3OWJiZDZhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxNzE0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWI5ODU5ZGJiODhmNDk2ODBiOWJmZTgzOTM5M2UxMDZkMmI1YWNjMzczYzQ0MGIyZGRiNjAyMmFjMDRkNTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92js0MeIPVxQGrlPVNrUF1uqjsUxK7gnN59a9aBe8Ys)

Alrighty, havent touched it since but ill re-check later. Im pretty sure I reinstalled the mod cleanly. Ill remove the thread since its most likely my end
