### ISSUE TITLE
Bots won't spawn

### ISSUE THREAD

**Issue by Setman590** [ineedbots/iw4x_bot_warfare#81]
Hi,

Went by the read me, mods\mp_bots start the server, go into game but there are no bots spawning
Did I miss something? Also added it in fs_game line mods\mp_bots

**Comment by ineedbots** [comment]
dvars? `set bots_manage_add 12` ?

**Comment by Setman590** [comment]
Thanks, missed that

**Comment by Setman590** [comment]
Is there a file where I can change bots names? Look through files but could not see it

**Comment by ineedbots** [comment]
not included with this mod anymore as its really client specific, but i believe just putting a mods.txt in the fs_game folder will do the trick
