### ISSUE TITLE
Bot Fillmode 2 and Fillmode 3 does not consider new maps yet. Only 2 bots are spawned.

### ISSUE THREAD

**Issue by Boxhead78** [ineedbots/iw4x_bot_warfare#88]
New maps aren't in function getGoodMapAmount so only 2 bots are spawned in DLC9 CLASSICS 3 maps and DLC10 MW3 maps.

**Comment by ineedbots** [comment]
Yep you are right, if someone wanted to make a PR to add maps, they can do so.

https://github.com/ineedbots/iw4_bot_warfare/blob/master/maps/mp/bots/_bot_utility.gsc#L1711

For reference
