### ISSUE TITLE
Bots don't use throwable weapons.

### ISSUE THREAD

**Issue by GHWhite419** [ineedbots/iw4x_bot_warfare#89]
Even with the "bots can nade" option enabled, bots won't equip/throw grenades, semtex, or throwing knives. They will throw grenades back if you throw at them, and will drop them with martyrdom. They also use plenty of other equipment.

**Comment by ineedbots** [comment]
they use grenades just fine
![image](https://github.com/ineedbots/iw4_bot_warfare/assets/751729/81df7cba-7312-40d7-b5c7-717f0d76c056)

**Comment by GHWhite419** [comment]
Okay gotcha, they seemed to never be using them when I would play. I was definitely wrong about Semtex and Throwing Knife, just would see them rarely use Frags. My mistake either way.
