### ISSUE TITLE
bots not using tactical nuke

### ISSUE THREAD

**Issue by Swaluver88** [ineedbots/iw4x_bot_warfare#90]
hello, every time about is about to get a nuke it either commits suicide or and dies. is there a fix?

**Comment by ineedbots** [comment]
what do you mean

**Comment by Swaluver88** [comment]
i have never seen a bot get a nuke. they get super close but then always find a way to die.

**Comment by ineedbots** [comment]
this is uhh, intentional game behavior? bots die whenever, the only fix would to have the bot play better, which would just mean better AI altogether
