### ISSUE TITLE
Everything is broken 

### ISSUE THREAD

**Issue by MANOUGG** [ineedbots/iw4x_bot_warfare#91]
The bots behave extremely dumb out of nowhere, tested this on multiple maps, maybe a new version of IW4X perhaps? But they are blind and walk into walls, often being stuck as well, it worked before on maps like invasion, afgan etc, but now it doesnt.

**Comment by MANOUGG** [comment]
To add further context, it's the same version of bot warfare, so this leads me to think that it is indeed IW4X somehow?

**Comment by MANOUGG** [comment]
To add more info, looked at the dev console, waypoints are in fact loading. But bots are fully unresponsive. If I change something like, bot can move = false, they keep moving

**Comment by ineedbots** [comment]
Yea, use the latest commit for now, I'll have to make a new release of botwarfare

**Comment by ineedbots** [comment]
U can use  v2.3.0

**Comment by MANOUGG** [comment]
Thanks! I'll close this, but thanks again for being so fast!
