### ISSUE TITLE
What is the command to enable/disable bots being able to use Tactical Nukes?

### ISSUE THREAD

**Issue by NightmaREE3Z** [ineedbots/iw4x_bot_warfare#96]
I've seen bots get nuke a few times, but chat always says "Admin disabled it for bots" 
I've not seen a way to enable/disable this, looking at Bot Warfare 2.30 files.

**Comment by ineedbots** [comment]
https://github.com/ineedbots/iw4_bot_warfare/blob/master/maps/mp/bots/_bot_script.gsc#L1049

and

https://github.com/ineedbots/iw4_bot_warfare/blob/master/maps/mp/bots/_bot_script.gsc#L989


its the bots_loadout_allow_op dvar

**Comment by NightmaREE3Z** [comment]
Ahh, forgot to tell you. 
At times they say that "I could've had a nuke but dumb admin disabled it for bots" then if you watch them play, they'll not have a nuke earned. Despite saying what they said about "Admin disabling it" 
However, at times. They just say "Get nuked, nerds!" or something and actually are able to call in the nuke. Despite me having that "bots_loadout_allow_op" dvar disabled.
