### ISSUE TITLE
Bots names

### ISSUE THREAD

**Issue by agrimpard** [ineedbots/iw4x_bot_warfare#97]
Is there a way to rename bots ?
Eventually something like that : https://cod4x.ovh/t/how-to-rename-bots-on-latest-version-of-bot-warfare/2603
A simple botnames.txt to add in the mod folder ...

**Comment by agrimpard** [comment]
Ok, finally found out how to !

You need to add a file `bots.txt` in the mod folder. For me the folder was : `C:\Program Files (x86)\Steam\steamapps\common\Call of Duty Modern Warfare 2\mods\mp_bots`.

The bots.txt file should look like this : 

```
BotName1,BOT
BotName2,BOT
BotName3,BOT
BotName4,BOT
```

One line per name, as many names as you want and `,BOT` is the "clan tag" which you can ommit.

**Comment by HabboCodes** [comment]
I just opened another issue for this exact problem, i didnt notice your issue before and have just tried your method however it doesnt seem to work?

can you provide a text sample of your bots.txt file?
